FROM arm64v8/maven:3.8.3-openjdk-17 AS splendorbuild
MAINTAINER maximilian schiedermeier
COPY server/src /usr/src/app/src
COPY server/pom.xml /usr/src/app
COPY server/savedgames /usr/src/app/savedgames
COPY server/savedgames /usr/app/savedgames

RUN mvn -f /usr/src/app/pom.xml clean package

## Discard Maven, run JAR file using JRE
FROM openjdk:17.0-jdk-slim

## Wait for the LobbyService to be ready (which in its turn waits for the DB)
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

# copy the jar from the build stage, expose the required port and run it.
COPY --from=splendorbuild /usr/src/app/target/SplendorServerApplication.jar /usr/app/SplendorServerApplication.jar
COPY --from=splendorbuild /usr/app/savedgames /usr/app/savedgames
EXPOSE 8080
#ENTRYPOINT ["java","-jar","/usr/app/SplendorServerApplication.jar"]

# allow debug if startup fails, with: docker run -it --entrypoint /bin/bash ls-xox -s
# RUN apk add --no-cache bash coreutils grep sed